# 程序终止

---

​		偶尔，一段代码会遇到无法处理的问题:

- 如果问题频繁发生，并且可以期望直接调用者处理它，则返回某种类型的返回码。
- 如果问题不常见，或者直接调用者不能处理它，则抛出异常。
- 如果问题严重到程序的普通部分无法处理它，那么就退出程序。

​		标准库提供了一些工具来处理最后一种情况(“退出程序”):

- ``exit(x)``:调用通过``atexit()``注册的函数，然后用返回值x退出程序。如果需要，查找``atexit()``，它基本上是与C语言共享的基本类型析构函数机制。
- `abort()`:立即无条件地退出程序，并返回一个表示不成功终止的值。有些操作系统提供了一些工具来修改这个简单的解释。
- `quick_exit (x)`:调用注册了``at_quick_exit()``的函数;然后以返回值x退出程序。
- `terminate()`:调用`terminate_handler`。默认的`terminate_handler`是`abort()`。

​		这些函数用于处理非常严重的错误。

- 它们不调用析构函数，他们不做普通和适当的清理。
- 处理程序在退出之前执行操作，操作必须非常简单，调用这些退出函数的原因之一是程序状态被破坏了。
  - 一种合理且流行的操作是“不依赖当前程序的任何状态，在定义良好的状态下重启系统”。
  - 另一种稍微有点冒险，但通常不是不合理的操作是“记录错误消息并退出”。
  - 写入日志消息可能是一个问题的原因是，I/O系统可能已经被导致调用exit函数的任何东西损坏了。

​		错误处理是最棘手的编程类型之一。即使是干净利落地退出程序也很难。任何通用的库都不应该无条件终止。



## ternimate status

​		**Normal termination** means the program has exited in an expected way. Note that the term `normal termination` does not imply anything about whether the program was successful (that’s what the `status code` is for). 

​		**Abnormal termination** means the program had some kind of unusual runtime error and the program couldn’t continue to run. 

## std::exit

​		`std::exit()` is a function that causes the program to terminate normally. 



​		`std::exit()` performs a number of cleanup function. First, objects with static storage duration are destroyed. Then some other miscellaneous file cleanup is done if any files were used. Finally, control is returned back to the OS, with the argument passed to `std::exit()` used as the `status code`.

​		Although `std::exit()` is called implicitly when function `main()` ends, `std::exit()` can also be called explicitly to halt the program before it would normally terminate. When `std::exit()` is called this way, you will need to include the `cstdlib` header.

```c++
#include <cstdlib> // for std::exit()
#include <iostream>

void cleanup()
{
    // code here to do any kind of cleanup required
    std::cout << "cleanup!\n";
}

int main()
{
    std::cout << 1 << '\n';
    cleanup();

    std::exit(0); // terminate and return status code 0 to operating system

    // The following statements never execute
    std::cout << 2 << '\n';

    return 0;
}
```

​		 the statements after the call to `std::exit()` never execute because the program has already terminated.

​		The `std::exit()` function does not clean up local variables in the current function or up the call stack.



## std::atexit

​		 allows you to specify a function that will automatically be called on program termination via `std:exit()`.

```c++
#include <cstdlib> // for std::exit()
#include <iostream>

void cleanup()
{
    // code here to do any kind of cleanup required
    std::cout << "cleanup!\n";
}

int main()
{
    // register cleanup() to be called automatically when std::exit() is called
    std::atexit(cleanup); // note: we use cleanup rather than cleanup() since we're not making a function call to cleanup() right now

    std::cout << 1 << '\n';

    std::exit(0); // terminate and return status code 0 to operating system

    // The following statements never execute
    std::cout << 2 << '\n';

    return 0;
}
```

-  `std::exit()` is called implicitly when `main()` terminates

  ​	 this will invoke any functions registered by `std::atexit()` if the program exits that way.

- the function being registered must take no parameters and have no return value.

- can register multiple cleanup functions using `std::atexit()`

  ​	they will be called in reverse order of registration (the last one registered will be called first).



## std::quick_exit / std::at_quick_exit

​		In multi-threaded programs, calling `std::exit()` can cause your program to crash (because the thread calling `std::exit()` will cleanup static objects that may still be accessed by other threads).

​		 For this reason, C++ has introduced another pair of functions that work similarly to `std::exit()` and `std::atexit()` called `std::quick_exit()` and `std::at_quick_exit()`. 

​		`std::quick_exit()` terminates the program normally, but does not clean up static objects, and may or may not do other types of cleanup. 

​		`std::at_quick_exit()` performs the same role as `std::atexit()` for programs terminated with `std::quick_exit()`.



std::abort 

​		The `std::abort()` function causes your program to terminate abnormally. 

> [Assert and static_assert](https://www.learncpp.com/cpp-tutorial/assert-and-static_assert/)) where `std::abort` is called implicitly.



## std::terminate

​		The `std::terminate()` function is typically used in conjunction with `exceptions` (we’ll cover exceptions in a later chapter).

​		Although `std::terminate` can be called explicitly, it is more often called implicitly when an exception isn’t handled (and in a few other exception-related cases).

​		By default, `std::terminate()` calls `std::abort()`.